name: rolodex

services:
  rsvp-automation:
    container_name: rsvp-automation
    build: .
    ports:
      - "5177:5173"
    networks:
      - webapps
    restart: unless-stopped
    env_file:
      - .env

networks:
  webapps:
    name: webapps
    external: true
